chore: restore previous publish workflow (revert), update min version of flutter_quill in test and extensions packages, removes pubspec_overrides.yaml

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -17,6 +17,11 @@ jobs:
     steps:
       - name: 📦 Checkout repository
         uses: actions/checkout@v4
+        # Needed for commit and push changes
+        with:
+          # TODO: Try to not hardcode the branch name
+          ref: master
+          fetch-depth: 0 # To get all tags
 
       - name: 📄 Upload LICENSE file to release assets
         uses: softprops/action-gh-release@v2
@@ -45,10 +50,45 @@ jobs:
       # - name: Update the authorization requests to "https://pub.dev" to use the environment variable "PUB_TOKEN".
       #   run: dart pub token add https://pub.dev --env-var PUB_TOKEN
 
-      
+      # Before publishing the new packages, update the version for all the packages first
 
-      # - name: 🔄 Check if package is ready for publishing
-      #   run: flutter pub publish --dry-run
+      # Extract version from the tag (handles the 'v' prefix)
+      - name: 🏷️ Extract version from tag as pubspec.yaml version
+        id: extract_version
+        run: |
+          version=$(echo ${GITHUB_REF} | sed 's/^refs\/tags\/v\(.*\)$/\1/')
+          echo "VERSION=${version}" >> $GITHUB_OUTPUT
+
+      - name: ✅ Validate extracted version format (should be pubspec.yaml valid version)
+        run: |
+          version=${{ steps.extract_version.outputs.VERSION }}
+          if [[ ! $version =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?(\+[0-9A-Za-z.-]+)?$ ]]; then
+            echo "❌ Invalid version format: $version. The version must be a valid pubspec.yaml version"
+            exit 1
+          fi
+
+      - name: 🏷️ Extract release tag
+        id: release_tag
+        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
+
+      - name: 📑 Fetch release notes from Github API and create a required file by the next step
+        run: dart ./scripts/create_version_content_from_github_release.dart "${{ github.repository }}" "${{ steps.release_tag.outputs.tag }}"
+
+      - name: 📝 Update version and CHANGELOG for all the packages
+        run: dart ./scripts/update_package_version.dart ${{ steps.extract_version.outputs.VERSION }}
+
+      - name: 💾 Commit updated version and CHANGELOG
+        id: auto-commit-action
+        uses: stefanzweifel/git-auto-commit-action@v5
+        with:
+          commit_message: "chore(version): update to version ${{ steps.extract_version.outputs.VERSION }}"
+
+      - name: 🔍 Verify changes made by the script
+        if: steps.auto-commit-action.outputs.changes_detected == 'true'
+        run: echo "✅ Changes have been committed."
+
+      - name: 🔄 Check if package is ready for publishing
+        run: flutter pub publish --dry-run
 
       - name: 📤 Publish flutter_quill
         run: flutter pub publish --force
@@ -60,4 +100,3 @@ jobs:
       - name: 📤 Publish flutter_quill_test
         run: flutter pub publish --force
         working-directory: ./flutter_quill_test/
-
